destination: _site/doc_pdf
url: "http://127.0.0.1:4005"
baseurl: "/doc_pdf"
port: 4005
output: pdf
product: mydoc
print: true
print_title: CMOR 
print_subtitle: version 3.6
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
